### ISSUE TITLE
Fetch list of all TLDs?

### ISSUE THREAD

**Issue by kevin-olbrich** [KnitCode/publicsuffix3#1]
Hi!

Thanks for this updated plugin, especially the get_tld part, that I needed.
Is it possible to fetch the list of nodes?
I am building a billing integration and I need to detect the TLD for a domain (works fine) but also generate a list of possible TLDs (which actually is the content of the public prefix file).

I need this list to manage (seed) pricelists.

Kind regards
Kevin

**Comment by KnitCode** [comment]
thank you. I've added an instance attribute called tlds, which you can retrieve. i haven't pushed this up to the pypi server, but it is on the development branch. In this case, the list will contain the extracted psl items, including any modifiers, e.g., wildcards. so, things like '*.amazonaws.com' will be in there. It is a list you can grab with psl.tlds, assuming you've created an instance called psl, and post process however you want.  the wildcards actually create new TLDs, so we can't apriori build a possible list, but if you had some vocabulary to plug in, you could. (you probably know all this, but recording for a future reader)

**Comment by KnitCode** [comment]
merged and uploaded to pypi.

**Comment by KnitCode** [comment]
@kevin-olbrich all of the changes for this module (publicsuffix3) have now been merged into the original publicsuffix2 and the pypi package updated. please use publicsuffix2 -- the attribute to get the tld list is included, as well.  I'll close this and remove the pypi project presently.

**Comment by kevin-olbrich** [comment]
Thanks for this addition!
A regression made it into the merge PR which I corrected and PR'd.
